
name: Build

on: [push, pull_request]

jobs:
  build-bam:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules
        shell: bash
        run: |
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
      - name: Checkout bam
        uses: actions/checkout@v2
        with:
          repository: matricks/bam
          ref: 07fbb5543c692f6b9a7f09e48c64e2368349a3a8
          path: ./bam

      - name: Prepare Linux
        if: contains(matrix.os, 'ubuntu')
        run: |
          sudo apt-get update -y
          sudo apt-get install libfreetype6-dev libsdl2-dev -y
          cd bam
          ./make_unix.sh

      - name: Prepare Windows
        if: contains(matrix.os, 'windows')
        run: |
          cd bam
          ./make_win64_msvc.bat

      - name: Build in debug mode
        run: ./bam/bam server_release
      - name: Test debug
        run: ./teeworlds_srv shutdown
