
name: Build

on: [push, pull_request]

jobs:
  build-bam:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules
        shell: bash
        run: |
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1

      - name: Checkout bam
        uses: actions/checkout@v2
        with:
          repository: matricks/bam
          ref: 4bffc62aa4bb184dfcd338d15d63903e561dcbed
          path: ./bam

      - name: Prepare Windows
        if: contains(matrix.os, 'windows')
        run: |
          start bam/make_win32_mingw.bat

      - name: Prepare Linux
        if: contains(matrix.os, 'ubuntu')
        run: |
          sudo apt-get update -y
          cd bam
          ./make_unix.sh

      - name: Build in Release mode
        if: contains(matrix.os, 'windows')
        run: |
          ls ./bam
          start bam/bam.exe server_release

      - name: Build in Release mode
        if: contains(matrix.os, 'ubuntu')
        shell: bash
        run: ./bam/bam server_release

      - name: Test Release
        run: ./DDNet-Server shutdown

      - name: Package
        run: |
          mkdir artifacts
          mv DDNet-Server artifacts

      - name: Upload Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: teeworlds-${{ matrix.os }}
          path: ./artifacts
